version: '3.4'

services:
  rabbitmq:
    build:
      context: .
      dockerfile: RabbitMqWithMqtt
    environment: 
      - RABBITMQ_DEFAULT_USER=test 
      - RABBITMQ_DEFAULT_PASS=test
    ports:
      - 15672:15672 # UI
      - 5672:5672   # main port
      - 1884:1883   # tcp
      - 15675:15675 # web-sockets
    container_name: rabbitmq_test
    networks:
       - test-network

networks:
  test-network:
    driver: bridge

